name: Publish react app

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: git pull origin production
      - run: git checkout production
      - run: git merge main
      - run: git push origin production
      - run: npm run build
      - run: git add .
      - run: git commit -m "built files"
      - run: git push origin production
